### ISSUE TITLE
2.249 to 2.271

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-jenkins#2]
2.249 to 2.271

**Comment by chendelin1982** [comment]
1. yum/apt installl or download jar package
2. upgrade solution verify and modify documentation
3. Which step for jar package unzip?
4. How can I upgrade a package using APT?

**Comment by chendelin1982** [comment]
Transfer jenkins to Websoft9dev/role_jenkins

**Comment by qiaofeng1227** [comment]
Done
