### ISSUE TITLE
Documentation does not match the project

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-jenkins#4]
## Language

- [x] Chinese
- [x] English

## Content error
不是docker 版本 ，网站显示使用了docker 

![image](https://user-images.githubusercontent.com/76861519/113953724-fd52dc80-984a-11eb-817d-5f31bbe73e40.png)

* URL: 
 https://support.websoft9.com/docs/jenkins/zh/stack-installation.html#%E5%87%86%E5%A4%87
* Description: 
* Screenshot

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
Done
